appname = backend
httpport = 8080
runmode = dev
EnableDocs = true

# konfigurasi database
db_driver = postgres
db_user = user
db_password = password
db_name = seapedia_db
host=127.0.0.1 
port=5432 
sslmode=disable