swagger: "2.0"
info: {}
basePath: /v1
paths:
  /account/account:
    get:
      tags:
      - account
      description: |-
        Tests the API
        <br>
      operationId: AccountController.AccountEndpoint
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Account'
        "403":
          description: body is empty
  /test/hello:
    get:
      tags:
      - test
      description: |-
        Tests the API
        <br>
      operationId: TestController.TestEndpoint
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Test'
        "403":
          description: body is empty
definitions:
  models.Account:
    title: Account
    type: object
  models.Group:
    title: Group
    type: object
  models.Test:
    title: Test
    type: object
  models.UserGroup:
    title: UserGroup
    type: object
