name: Build & Deploy Backend to DOM Cloud

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.26' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Display Go version
      run: go version
    - name: Install Beego
      run: go install github.com/beego/bee/v2@latest
    - name: Install dependencies and build application
      working-directory: backend
      run: |
        go mod tidy
        go build -o app
    - name: Test SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_KEY }}
        script: |
          whoami
          pwd
          echo $HOME
          mkdir -p public_html/test
          echo OK
    - name: Deploy application
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_KEY }}
        port: 22
        source: "app"
        target: "public_html/public"
    - name: Deploy conf files
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_KEY }}
        port: 22
        source: "conf/"
        target: "public_html/public"
    - name: Deploy static files
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_KEY }}
        port: 22
        source: "static/"
        target: "public_html/public"
    - name: Deploy view files
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_KEY }}
        port: 22
        source: "views/"
        target: "public_html/public"
    - name: Restart application
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_KEY }}
        script: restart || true